### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by roman-yagodin**
- Translate new (untranslated) strings.
- Translate "upload" as "выгрузка".
- Sync ending punctuation and fix some other QA issues detected by crowdin.

### CODE REVIEW

**Review by bdukes — APPROVED** [review]

**Comment by roman-yagodin** [comment]
Should I take any additional actions in order this to be merged?

**Comment by bdukes** [comment]
@mitchelsellers are you ready to give this an approval?

**Review by mitchelsellers — APPROVED** [review]
I don’t know Russian so trusting translation

**Comment by roman-yagodin** [comment]
Thanks!

**Pull request merged**
