### PR TITLE
Bug/dnn 7667

### PR DESCRIPTION
**Pull request by agrueso**

### CODE REVIEW

**Comment by agrueso** [comment]
I have made the change to ensure that classes are serializable.
You can see more details in the following link: https://dnntracker.atlassian.net/browse/DNN-7667

**Comment by ohine** [comment]
Quite a few of these plugins were causing issues and that's why I removed them. Hopefully this was fully tested before merging back into the project.

**Comment by agrueso** [comment]
Thanks for the note Oliver. Do you remember what plugins were causing that problems? I had to add them again because the Editor was not able to be shown on Edit Content Dialog.

**Comment by ohine** [comment]
This is because of the default settings, I just found where they're being set and my next commit was going to only load the dnnpages plugin. I believe CodeMirror was causing the most issues, and we certainly don't need to include and/or load every one of them by default. I'm going to revert this commit so we can split up the serialization and plugins into two separate pull requests.

**Comment by agrueso** [comment]
Ok.
But I'd like to let you know that the development branch without my changes is not stable and the CKEditorProvider is not usable, so the DNN HTML module cannot be use.

I would have prefrerred to keep up this changes in order to ensure that serialization and other changes could be tested and create a new pull request with all changes needed to remove unnecessary or conflicting plugins

**Comment by ohine** [comment]
I will commit a change to the default settings to restore the editor in its current state. The serialization issue is a good fix, but I'm not willing to accept loading all of the plugins just to get the serialization issue closed.

**Comment by agrueso** [comment]
Perfect. That could be a solution. Let me know when you commit your changes. The serialization issues is still pending to be moved to testing. So I will move it when your changes were added. Do you agree?

**Comment by ohine** [comment]
Yup, I agree! I just made the change - https://github.com/DNN-Connect/CKEditorProvider/commit/b4bf3f648143723adfef9fb4a01b06f70aaa8c7a

I haven't tested this yet on an upgrade (it should fix clean installs for sure), but if the editor still doesn't load the settings file under _default and the portal home directory will need to be cleared. I'm trying to wrap my head around the multiple methods for settings in the editor to refactor them into something easier to understand and maintain.

**Pull request merged**
