### PR TITLE
DNN-8047: CKEditor should not be set as default Html Provider on Upgrades.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by ohine** [comment]
The version needs to be updated to v1.0.2 and not v8.0.0 in this pull request

**Comment by ohine** [comment]
Also, pull requests shouldn't be merged before the automatic build checks complete successfully.

**Comment by zyhfish** [comment]
Please don't revert my PR, i need test it in build agent.

**Comment by ohine** [comment]
Pull requests do not need to be merged for testing. If you wait for the build agent to finish, it will generate an install zip from the pull request. Plus, they version is incorrect which is why it was reverted. Please fix this issues and resubmit the suggested modification.

**Comment by sleupold** [comment]
do NOT touch the provider package for upgrade scenarios.
If you don't want CKEditor to be installed as default editor provider, rename the install package to .resources. This way, the superuser may decide, whether to install (and uninstall other editors).
We should stay away from installing extensions, which might not be used

**Comment by jbrinkman** [comment]
@sleupold We want the CKEditor installed for all users.  We only want it to be default for new installs.  This installation lights up the ability to switch providers in the HTML Editor Manager.  This is consistent with how we treat all new features.

**Comment by sleupold** [comment]
@jbrinkman I don't see a benefit in installing extensions, which are not being used. This only increases memory consumption and risks. Ideally, each site should remove all unused extensions (that's what I always do first, when I need to fix or taking over a DNN website of a client)

**Comment by sleupold** [comment]
Note that a version 1 will not upgrade existing providers from Ingo. This should be intended behavior, if Ingo plans to continue development of his provider. Otherwise it would be useful to use a version number much higher than the original provider.

**Comment by jbrinkman** [comment]
@sleupold Ingo's provider and this provider have different names and namespaces.  This version should not affect Ingo's regardless of the version number.  
Part of the challenge we have with DNN when introducing new features is that people are generally not aware of them.  While you might be diligent about going to see what is "installable" many users do not, and are unaware of the new capabilities.  We try to walk a fine line between forcing new features on users during upgrades and making features available with minimal effort. While there are many opinions on what the proper approach is, this is what we have chosen to do in this case - even knowing that some people will have a different opinion.

**Comment by ohine** [comment]
My only issue was the version change to v8. We do not want to jump from v1 to v8 for the ckeditor. We still have a lot of work to do before a major version bump. If the provider isn't active on upgrades, that's aok with me.

**Comment by ashishpd** [comment]
@ohine the version number of the Provider (second line in the .dnn file) was left at 01.00.01. The version number for _upgradeVersionsList_ was made 08.00.00.

You want both of these to be 01.00.02? We will submit a new PR once you confirm. Thanks.

**Comment by jbrinkman** [comment]
@ashishpd 08.00.00 is not a valid version for CKEditor so it makes no sense to be in the upgradeVersionList.  In looking at DNN source code, that should be a list of the module versions that should be passed to the IUpgradeable call.  Based on my understanding of the code, it seems that this value should not be any greater than the actual value of the extension version.

```
//get the list of applicable versions
string[] UpgradeVersions = message.Attributes["UpgradeVersionsList"].Split(',');
foreach (string Version in UpgradeVersions)
{
    //call the IUpgradeable interface for the module/version
    string Results = ((IUpgradeable) controller).UpgradeModule(Version);
    //log the upgrade results
    var log = new LogInfo {LogTypeKey = EventLogController.EventLogType.MODULE_UPDATED.ToString()};
    log.AddProperty("Module Upgraded", BusinessControllerClass);
    log.AddProperty("Version", Version);
    if (!string.IsNullOrEmpty(Results))
    {
        log.AddProperty("Results", Results);
    }
    LogController.Instance.AddLog(log);
}
```

**Comment by ohine** [comment]
@ashishpd correct, the upgrade version needs to match the module version. Since v1.0.1 already shipped, it needs to jump to v1.0.2 for it to run successfully on new and upgraded sites. My understanding is exactly as @jbrinkman described above.

**Pull request merged**
