### PR TITLE
Fix case-sensitive file extension comparisons

### LINKED ISSUE #132: html editor cannot show imagefiles with file-extensions as uppercase
## Description of bug
The html editor cannot show imagefiles with file-extensions being uppercase.

## Steps to reproduce

1. Make sure to use dnn v 9.4.1 or 9.4.2 and DNN Connect CKEditor Provider version 1.0.7 and DNN Connect CKEditor as default html-editor.

2. Log in and click on "Site Assets" under "Manage".

3. Make sure you have a few image-files in a directory. Make sure you have both imagefiles with lowercase extensions (like *.jpg) and imagefiles with uppercase extensions (like *.JPG).

4. Navigate to a page in the site, and activate editmode (click on pencil). Then make sure you have the html modul in a pane. Open the html editor and click the image icon in order to insert an image.

5. Click "Browse on server". 

## Current result
Find the directory where the image files are located. Now you will only see the imagefiles which have the extension as lowercase.

## Expected result
We have obviously expected to see also the imagefiles with extensions as uppercase

## Error log
No errorlogs shown

## Additional context
We have tested on another site using DNN 9.3.2 and DNN Connect CKEditor Provider version 1.0.5. On this site no problems as above occur.

## Affected version

* [X ] 9.4.1 latest supported release
* [X ] 9.4.2 latest supported release

## Affected browser
Chrome and Safari are not tested. Browsers below all react as described.
* [ X] Firefox
* [ X] Internet Explorer
* [X ] Edge

## Environment on server

OS Version:
Microsoft Windows NT 6.2.9200.0

Web Server Version:
Microsoft-IIS/8.0
.NET Framework Version:
4.0.30319.42000

### PR DESCRIPTION
**Pull request by bdukes**
Fixes #132

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]

**Review by valadas — APPROVED** [review]
Looks great to me, should me merge into development or is there more to the process here? Do we need to bump the version manually, I am not familiar with the process on this repository

**Comment by bdukes** [comment]
From what I can see, we'll need to also do a version bump before DNN 9.4.3 comes out, but that can be a separate PR

**Comment by valadas** [comment]
Yes, for upgrades support each new change between Dnn versions will need a bump or it won't upgrade.

**Comment by bdukes** [comment]
Is this change good to merge?

**Comment by mitchelsellers** [comment]
@bdukes Shouldn't this target 9.x branch?

**Comment by bdukes** [comment]
I didn't see any `release` branches in this repo, would you like me to create one?

**Comment by mitchelsellers** [comment]
Crud, sorry, wrong repo!

**Pull request merged**
