### PR TITLE
Changes for Addition of Host level settings

### PR DESCRIPTION
**Pull request by JoshuaBradley**
This allows for Host level settings so that it won't have to be configured for every site. This also fixes the problem with trying to modify settings for a site other than the one you are currently on. I handle the Host level setting Roles by finding common roles across all portals, wasn't sure of the best way to handle that.

### CODE REVIEW

**Comment by ohine** [comment]
It appears the references were all updated to a local set instead of the nuget package. It also looks like an upgrade to .net 4.5 was included, it would be great if this could be rolled back to .net 4 since we are targeting dnn 7.4.0+. Fixing those should hopefully get the appveyor ci build to succeed.

**Comment by JoshuaBradley** [comment]
Yeah, sorry about that. Should be fixed now.

**Comment by JoshuaBradley** [comment]
CI will fail because I changed a bunch of stuff to use C# 6 while I was in there. Should I try to revert these changes, or do you want to change the CI build to point at VS 2015 MS Build binaries? Not sure if you're wanting to put a dependency on VS 2015, but since DNN did I figured this could as well.

**Comment by ohine** [comment]
If it's not too much of a pain to revert the C#6 bits, that would be ideal. I'd really like to keep dnn7 support going if it's not too much trouble.

**Comment by bdukes** [comment]
I don't have any opinion about using C# 6 in this project; however, you should still be able to target DNN 7 (i.e. target .NET 4) while writing C# 6, if you want.

**Comment by bdukes** [comment]
@ohine is the build server going to be able to support C# 6, or do we need to do the work to revert to C# 5?  Would it be possible to get access to the build server to enable that support going forward?

**Comment by ohine** [comment]
@bdukes I've already attempted to modify the build server to support c#6. I need to contact appveyor next to see if it's something broken on their end or on my account. Let me see if I can expose the build server to additional accounts, or maybe we can take this offline and figure out the best way to get this integrated into the next official release.

**Pull request merged**
