### PR TITLE
Char and Word Count Missing in CKEditor

### LINKED ISSUE #109: Char and Word Count Missing in CKEditor
### Preconditions 

Install any DNN instance starting from 9.1.1

### Steps to reproduce

1. Login as a AdminUser
2. Create new published page
3. Edit any HTML module to open CKE
4. Click on Custom Editor Options
5. Go to Editor Config tab
6. Scroll down and make sure ShowCharCount/ShowWordCount settings are checked

### Current behavior 
Neither word count nor char count info is not displayed on the toolbar.

### Expected behavior 
Word/Char count info should be displayed on the toolbar according to Editor WordCount settings.

### PR DESCRIPTION
**Pull request by mikebigun**
fixes https://github.com/DNN-Connect/CKEditorProvider/issues/109

Word count plugin is added as per https://ckeditor.com/cke4/addon/wordcount
- wordcount and notification folders/scripts are extracted to CKEditor `plugins` folder
- `extraPlugins` setting is updated to include newly installed plugins

See DEMO: [demo](https://drive.google.com/file/d/1LsP6C65sh2I1zmA9vIj3H_HohPjI_k5c/view?usp=sharing)

### CODE REVIEW

**Comment by daguiler** [comment]
WordCount plugin was removed [here](https://github.com/DNN-Connect/CKEditorProvider/commit/b4bf3f648143723adfef9fb4a01b06f70aaa8c7a). Do you remember why @ohine ?

**Comment by daguiler** [comment]
I found some info here: https://github.com/DNN-Connect/CKEditorProvider/pull/13.
It seems all final commits of the [1.0.1.5 tag](https://github.com/DNN-Connect/CKEditorProvider/commits/1.0.1.5) were about removing extra plugins.

**Comment by mikebigun** [comment]
Team, do you have any conclusion on this? Let me know if you have any concerns to have this merged.
@ohine @daguiler

**Comment by sleupold** [comment]
AFAIR, most of the CKEditor extensions were eliminated when forking the extension in DNN 8

**Review by daguiler — APPROVED** [review]

**Review by bdukes — APPROVED** [review]

**Pull request merged**
