### PR TITLE
Resolves issue #149

### PR DESCRIPTION
**Pull request by WillStrohl**
Resolves issue #149

### CODE REVIEW

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
It should be noted that [this is the default for this plugin](https://github.com/ckeditor/ckeditor4/blob/4f621d0ead1d2cc4ba2ff618f723f80159b6ae22/plugins/templates/templates/default.js#L27), so updating the plugin will overwrite your change.  Maybe you should also open a plugin there.

Also, it's a little tricky to find, but you can configure the site to use a different set of templates than that default set.  First you need to find the HTML Editor Manager (Settings/Gear section of Persona Bar -> Site Settings "page" in Persona Bar -> Site Behavior tab -> More tab -> HTML Editor Manager button).  Then in the HTML Editor Manager, you can expand the Configuration section of the Main Settings tab and select a file for the Editor Templates file setting (which means you need a JS file in your portal file system, requiring you to adjust allowed file extensions).  _Then_, go to the Editor Config tab and update the `templates` setting to remove `default` and add the name of your group of templates.

**Comment by WillStrohl** [comment]
Yeah, I thought about those things too.  This is primarily about a first-time use experience for folks.  :)

**Review by david-poindexter — APPROVED** [review]
Thanks @hismightiness - great catch!  🎉

**Comment by david-poindexter** [comment]
I guess my reviews are not "approving" in this repo for some reason.  @bdukes are you able to handle?  Also, #149 will need to be manually closed upon merge due to missing syntax to auto-close.

**Pull request merged**
