### PR TITLE
Bug/dnn 7667

### PR DESCRIPTION
**Pull request by agrueso**
These changes include the Serialization fix and also the deletion of unnecessary extra plugins files

### CODE REVIEW

**Comment by agrueso** [comment]
Also complementary to Oliver's last commit, I have deleted the references to unnecessary extra plugins in order to allow Editor can work successfully

**Comment by ohine** [comment]
@agrueso I don't see the commit for the serialization fix.

**Comment by agrueso** [comment]
Ups, thanks @ohine . I have added that change in a new pull request Could you merge it?  It is number #17

**Comment by ohine** [comment]
Sure thing @agrueso 
When the new pull request comes in I'll review and merge.

**Comment by agrueso** [comment]
Thanks Oliver for your help. I think my workmate Francesco already has reviewed that.

**Pull request merged**
